; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{1E4B9028-9164-4453-846F-1F2C2D7A6C9E}
AppName=SearchGems
AppVersion=2.0
;AppVerName=SearchGems 2.0
AppPublisher=Luis Duno Castellano
AppPublisherURL=http://dunocgame.blogspot.com/
AppSupportURL=http://dunocgame.blogspot.com/
AppUpdatesURL=http://dunocgame.blogspot.com/
DefaultDirName={pf}\SearchGems
DisableProgramGroupPage=yes
LicenseFile=C:\Users\DC\Desktop\SearchGems\license.txt
OutputDir=C:\Users\DC\Desktop\SearchGems\Stup
OutputBaseFilename=SearchGems
SetupIconFile=C:\Users\DC\Desktop\SearchGems\favicon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\DC\Desktop\SearchGems\dist\SearchGems\SearchGems.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DC\Desktop\SearchGems\dist\SearchGems\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\SearchGems"; Filename: "{app}\SearchGems.exe"
Name: "{commondesktop}\SearchGems"; Filename: "{app}\SearchGems.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\SearchGems"; Filename: "{app}\SearchGems.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\SearchGems.exe"; Description: "{cm:LaunchProgram,SearchGems}"; Flags: nowait postinstall skipifsilent

